# This is a basic workflow to help you get started with Actions

name: CONTINOUS DEPLOYMENT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env :
      working-directory: ./website
      GIT_USER : AmineZAMANI

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
    # Runs a single command using the runners shell
    - name: install
      run: npm install 
      working-directory: ${{env.working-directory}}

    # Runs a single command using the runners shell
    - name: build
      run: npm run build 
      working-directory: ${{env.working-directory}}
      
    # Runs a single command using the runners shell
    #- name: deploy
    #  run: npm run publish-gh-pages
    #  working-directory: ${{env.working-directory}}
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: /website/build/ # The folder the action should deploy.
    
    #- name: Deploy
     # uses: peaceiris/actions-gh-pages@v3
      #with:
       # github_token: ${{ secrets.GITHUB_TOKEN }}
        #publish_dir: ./website/build/BadrMobileRnWiki/en/
      
      
